version: '3.4'
services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    volumes:
      - ${PWD}${MYSQL_PATH-/db/mysql_datadir}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD:
    networks:
      ideaplus_network:
        ipv4_address: ${IP_PREFIX}.0.3
    ports:
      - "10003:3306"

  php:
     depends_on:
       - db
     image: wyveo/nginx-php-fpm:php74
     container_name: ${PROJECT_NAME}_php
     volumes:
       - ${PWD}:/usr/share/nginx
       - ${PWD}/host_config/nginx-docker.conf:/etc/nginx/conf.d/default.conf
     networks:
       ideaplus_network:
         ipv4_address: ${IP_PREFIX}.0.2
     ports:
      - "80:80"
     restart: always
     environment:
       TZ: Europe/Moscow
       ERRORS: 0
       ENABLE_XDEBUG: 1
       SKIP_CHOWN: 1
       SKIP_COMPOSER: 0
       REMOVE_FILES: 0
       
networks:
  ideaplus_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_PREFIX}.0.0/24
 
